url: "https://mukuljangra.com"

site_name: "Mukul J."
site_tagline: "By day, I work as an Android Engineer. I'm passionate about privacy, free speech, and open-source technologies."
site_github: "https://github.com/jangramukul"
site_nostr: "https://primal.net/p/npub1nxzck4kpc3pegzajcktvvfe85rc3mxqgffc0swfw556hwf7g9c3s2c6epl"
site_mastodon: "https://mastodon.social/@mukuljangra"
site_twitter: "https://x.com/iammukuljangra"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

plugins:
  - jekyll-redirect-from

collections:
  presentations:
    output: true
    permalink: /:title/

  podcasts:

  notes:
    output: true
    permalink: /:title/

include:
  - '.well-known'
  - '_redirects'

exclude:
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - out
  - capture
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.txt
  - CNAME
