url: "https://mukuljangra.com"

site_name: "Mukul Jangra"
site_tagline: "Code for Android. Fight for Digital Rights & Privacy. Resist Surveillance."
site_github: "https://github.com/m8kul"
site_mailto: "mailto:contact@mukuljangra.com"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

plugins:
  - jekyll-redirect-from

collections:
  presentations:
    output: true
    permalink: /:title/

  podcasts:

  notes:
    output: true
    permalink: /:title/

include:
  - '.well-known'
  - '_redirects'

exclude:
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - out
  - capture
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.txt
  - CNAME
