url: "https://mukuljangra.com"

site_name: "Mukul Jangra"
site_url: "mukuljangra.com"
site_title: "Mukul"
site_tagline: "By day, I work as an Android Engineer. I'm passionate about Android, Security, Architecture, Privacy, and Opensource technologies."
site_github: "https://github.com/jangramukul"
site_mastodon: "https://mastodon.social/@mukuljangra"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

plugins:
  - jekyll-redirect-from

collections:
  articles:
    output: true
    permalink: /article/:title/

  newsletters:
    output: true
    permalink: /newsletter/:title/

include:
  - '.well-known'
  - '_redirects'

exclude:
  - 'node_modules'
  - 'scripts'
  - 'vendor'
  - out
  - capture
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - README.md
  - LICENSE.txt
